LIBFARMBOT_MAJOR := 0
LIBFARMBOT_MINOR := 1
LIBFARMBOT_REL   := 0

LIBFARMBOT_DIR         ?= $(PWD)
LIBFARMBOT_OUT_DIR     := $(LIBFARMBOT_DIR)/out
LIBFARMBOT_INCLUDE_DIR := $(LIBFARMBOT_DIR)/include
LIBFARMBOT_SRC_DIR     := $(LIBFARMBOT_DIR)/src
LIBFARMBOT_TEST_DIR    := $(LIBFARMBOT_DIR)/test
LIBFARMBOT_VENDER_DIR  := $(LIBFARMBOT_DIR)/vendor

LIBFARMBOT             := $(LIBFARMBOT_OUT_DIR)/libfarmbot.so
LIBFARMBOT_SRC         := $(wildcard $(LIBFARMBOT_SRC_DIR)/*.c)
LIBFARMBOT_OBJ         := $(LIBFARMBOT_SRC:.c=.o)

LIBFARMBOT_TEST_SRC    := $(wildcard $(LIBFARMBOT_TEST_DIR)/*.c)
LIBFARMBOT_TEST_OBJ    := $(LIBFARMBOT_TEST_SRC:.c=.o)
LIBFARMBOT_TEST        := $(LIBFARMBOT_TEST_SRC:.c=.test)
# LIBFARMBOT_TEST      := $(patsubst $(LIBFARMBOT_TEST_DIR)/%,$(LIBFARMBOT_OUT_DIR)/%,$(LIBFARMBOT_TEST))

ALL := $(LIBFARMBOT_OUT_DIR) $(LIBFARMBOT) $(LIBFARMBOT_TEST)
CLEAN :=
PHONY := all clean test

include $(LIBFARMBOT_VENDER_DIR)/cJSON/cJSON.mk

INCLUDE_CFLAGS := \
-I$(LIBFARMBOT_INCLUDE_DIR) \
-I$(cJSON_INCLUDE_DIR)

CFLAGS ?= -std=c11 -g -DDEBUG -c -fPIC --shared $(INCLUDE_CFLAGS)
LDFLAGS ?= -lcurl -fPIC --shared

.PHONY: $(PHONY)
.DEFAULT_GOAL: all

all: $(ALL)

clean: $(CLEAN)
	$(RM) $(LIBFARMBOT_OBJ)
	$(RM) $(LIBFARMBOT)
	$(RM) $(LIBFARMBOT_TEST_OBJ)

test: $(LIBFARMBOT_TEST)
	LD_LIBRARY_PATH=$(LIBFARMBOT_OUT_DIR) test/login_test.test


$(LIBFARMBOT_SRC_DIR)/%.o: $(LIBFARMBOT_SRC_DIR)/%.c
	$(CC) $(CFLAGS) $< -o $@

$(LIBFARMBOT): $(LIBFARMBOT_OBJ)
	$(CC) $(LDFLAGS) $(LIBFARMBOT_OBJ) -o $@

$(LIBFARMBOT_TEST_DIR)/%.o: $(LIBFARMBOT_TEST_DIR)/%.c
	$(CC) -o $@ -c -g -std=c11 -DDEBUG -I$(LIBFARMBOT_INCLUDE_DIR) $<

$(LIBFARMBOT_TEST_DIR)/%.test: $(LIBFARMBOT_TEST_DIR)/%.o
	$(CC) -o $@ -L$(LIBFARMBOT_OUT_DIR) $< -lfarmbot

$(LIBFARMBOT_OUT_DIR):
	mkdir -p $@
